config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users, only: %i(show new create update)
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :account_activations, only: :edit
  resources :sub_forums
  resources :password_resets, only: %i(new create edit update)
  resources :sub_forums
  resources :members, only: %i(create destroy update)
  resources :password_resets, only: %i(new create edit update)
  resources :members, only: %i(create destroy)
  get "/submit", to: "posts#new"
  post "/submit", to: "posts#create"
  resources :posts, only: %i(show update)
  post "/posts/:id", to: "post_interactions#update"
  get "/search", to: "searchs#new"
  get "/users/:id/created_sub_forums",
    to: "users#show_created_sub_forums", as: "created_sub_forums"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @trending_sub_forums = SubForum.trending_forums
    @trending_posts = Post.trending_posts
    @popular_posts = if current_user && params[:popular]
                       Post.personal(current_user).popular_posts
                     else
                       Post.popular_posts
                     end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<div class="row has-margin-row">
  <div class="col-12">
    <h4><%= t ".trending_today" %></h4>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <div class="card-deck">
      <% 4.times do %>
        <%= render "shared/trending_post" %>
      <% end %>
    </div>
  </div>
</div>
<div class="row has-margin-row">
  <div class="col-12">
    <h4><%= t ".popular" %></h4>
  </div>
</div>
<div class="row">
  <div class="col-9">
    <% 10.times do %>
      <%= render "shared/post_preview" %>
    <% end %>
  </div>
  <div class="col-3">
    <div class="card">
      <div class="card-body">
        <%= link_to t("create_post"), submit_path,
              class: "btn btn-primary full-width"%>
        <%= link_to t(".create_sub_forum"), new_sub_forum_path,
              class: "btn btn-primary full-width" %>
      </div>
    </div>
    <br>
    <div class="card">
      <div class="card-header">
        <%= t "static_pages.home.trending_forums" %>
      </div>
      <ul class="list-group list-group-flush">
        <%= render partial: "shared/trending_sub_forum", collection: @trending_sub_forums %>
      </ul>
    </div>
  </div>
</div>