config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users, only: %i(show new create update)
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :account_activations, only: :edit
  resources :sub_forums
  resources :password_resets, only: %i(new create edit update)
  resources :sub_forums
  resources :members, only: %i(create destroy update)
  resources :password_resets, only: %i(new create edit update)
  resources :members, only: %i(create destroy)
  get "/submit", to: "posts#new"
  post "/submit", to: "posts#create"
  resources :posts, only: %i(show update)
  post "/posts/:id", to: "post_interactions#update"
  get "/search", to: "searchs#new"
  get "/users/:id/created_sub_forums",
    to: "users#show_created_sub_forums", as: "created_sub_forums"
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
       <%= "#{t("the_form_contains")} #{pluralize(object.errors.count, "error")}." %>
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_post_preview.html.erb
<div class="card popular-post">
  <div class="card-header">
    Forum name
  </div>
  <div class="card-body">
    <h5 class="card-title">Post title</h5>
    <p class="card-text">Created at </p>
    <a href="#" class="btn btn-primary">Go to post</a>
  </div>
</div>

app/views/shared/_sub_forum.html.erb
<div class="col-4">
  <div class="card" style="margin-bottom: 10px">
    <div class="card-body">
      <h5 class="card-title"><%= sub_forum.name %></h5>
      <p class="card-text"><%= sub_forum.description %></p>
      <p class="card-text">
        <small class="text-muted">Created at 3 mins ago</small>
      </p>
      <%= link_to t("view"), sub_forum, class: "btn btn-primary" %>
      <% if current_user && current_user?(sub_forum.user) %>
        <%= link_to t("update"), edit_sub_forum_path(sub_forum), class: "btn btn-primary" %>
        <%= link_to t("delete"), sub_forum, method: :delete, class: "btn btn-danger float-right" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_trending_post.html.erb
<div class="card text-white" style="background-color: blue;">
  <div class="card-body">
    <h5 class="card-title">
      <%= link_to post.title, post, style: "color: white;"%>
    </h5>
    <p class="card-text"><%= post.content %></p>
    <p class="card-text">
      <%= "#{t("posted_at")} #{time_ago_in_words(post.created_at)} ago"%>
    </p>
  </div>
</div>

app/views/shared/_trending_sub_forum.html.erb
<% if current_user.nil? %>
  <li class="list-group-item">
    <%= link_to trending_sub_forum.name, trending_sub_forum %>
    <%= form_for :member, url: members_path do |f| %>
      <%= f.submit t("join"), class: "btn btn-primary float-right" %>
    <% end %>
  </li>
<% else %>
  <li class="list-group-item">
    <%= link_to trending_sub_forum.name, trending_sub_forum %>
    <div id=<%= "join_form_#{trending_sub_forum.id}" %> >
      <% if current_user.joined_forums?(trending_sub_forum) %>
        <%= render "members/leave", forum_id: trending_sub_forum.id %>
      <% else %>
        <%= render "members/join", forum_id: trending_sub_forum.id %>
    <% end %>
    </div>
  </li>
<% end %>