config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users, only: %i(show new create update)
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :account_activations, only: :edit
  resources :sub_forums
  resources :password_resets, only: %i(new create edit update)
  resources :sub_forums
  resources :members, only: %i(create destroy update)
  resources :password_resets, only: %i(new create edit update)
  resources :members, only: %i(create destroy)
  get "/submit", to: "posts#new"
  post "/submit", to: "posts#create"
  resources :posts, only: %i(show update)
  post "/posts/:id", to: "post_interactions#update"
  get "/search", to: "searchs#new"
  get "/users/:id/created_sub_forums",
    to: "users#show_created_sub_forums", as: "created_sub_forums"
end

app/models/sub_forum.rb
class SubForum < ApplicationRecord
  has_many :members, dependent: :destroy
  has_many :users, through: :members
  has_many :posts, through: :members

  belongs_to :user
  validates :user_id,
    presence: true
  validates :name,
    presence: true,
    length: {maximum: Settings.maximum_name_length},
    uniqueness: {case_sensitive: true}
  scope :trending_forums, ->{last(Settings.number_of_trending_forums).reverse}

  def self.search q
    ApplicationController.helpers.search q, ngram = 3, SubForum, Settings.relevant_record,
      [:id, 0], [:name, Settings.sub_forum.name],
      [:description, Settings.sub_forum.description]
  end
end

app/controllers/sub_forums_controller.rb
class SubForumsController < ApplicationController
  before_action :find_forum_by_id, only: %i(show destroy edit update)
  before_action :check_correct_user, only: %i(destroy update)

  def new
    @sub_forum = SubForum.new
  end

  def create
    @sub_forum = current_user.sub_forums.build sub_forum_params

    if @sub_forum.save
      current_user.join @sub_forum, Settings.admin_forum
      redirect_to @sub_forum
    else
      render :new
    end
  end

  def show
    @mods = @sub_forum.members.type Settings.mod_forum
    @posts = @sub_forum.posts
  end

  def edit
    @admin = @sub_forum.members.type Settings.admin_forum
    @mods = @sub_forum.members.type Settings.mod_forum
    @normal_members = @sub_forum.members.type Settings.member_forum
    @banned_members = @sub_forum.members.type Settings.banned_user
  end

  def update
    if @sub_forum.update_attributes(sub_forum_params)
      flash[:success] = t ".sub_forum_updated"
      redirect_to edit_sub_forum_path(@sub_forum)
    else
      render root_url
    end
  end

  def destroy
    @sub_forum.destroy
    redirect_to request.referrer || root_url
  end

  private

  def sub_forum_params
    permit_symbols = [:description]
    permit_symbols << :name if params[:action] == "create"
    params.require(:sub_forum).permit permit_symbols
  end

  def check_correct_user
    return if current_user == @sub_forum.user
    flash[:danger] = t "not_authorized"
    redirect_to root_url
  end

  def find_forum_by_id
    @sub_forum = SubForum.find_by(id: params[:id])
    return if @sub_forum
    flash[:danger] = t ".sub_forum_not_found"
    redirect_to root_url
  end
end

app/views/sub_forums/_edit_sub_forum_form.html.erb
<div class="card">
  <div class="card-header">Subforum details</div>
  <div class="card-body">
    <h5 class="card-title"><%= @sub_forum.name %></h5>
    <div class="row">
      <div class="col-6">
        <%= pluralize(@sub_forum.members.size, t("member_string")) %>
      </div>
      <div class="col-6" style="border-left: solid 1px;">
        Lorem ifsum
      </div>
    </div>
    <hr>
    <%= form_for(@sub_forum) do |f| %>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <%= f.submit t(".update_description"),
            class: "btn btn-lg btn-primary btn-block full-width" %>
    <% end %>
  </div>
</div>

app/views/sub_forums/_post_preview_list.html.erb
<% posts.each do |post| %>
  <div class="card popular-post">
    <div class="card-body">
      <div class="row">
        <div class="col-1">
          <i class="material-icons">
            arrow_drop_up
          </i>
          <i class="material-icons">
            arrow_drop_down
          </i>
        </div>
        <div class="col-11">
          <h5>
            <%= link_to post.content, post %>
          </h5>
          <p class="card-text"><%= "#{t ".posted_by"} #{post.member.user.name}" %> </p>
          <%= link_to t(".comments_string"), nil %>
          <%= link_to t(".bookmark"), nil %>
          <%= link_to t(".report"), nil %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/sub_forums/_sub_forum.html.erb
<%= link_to sub_forum.name, sub_forum_path(sub_forum.id) %><br>
<%= sub_forum.description %><br><br>

app/views/sub_forums/_sub_forum_details.html.erb
<div class="card mb-3">
  <div class="card-header">Subforum details</div>
  <div class="card-body">
    <h5 class="card-title"><%= @sub_forum.name %></h5>
    <div class="row" style="margin-bottom: 5px">
      <div class="col-6">
        <%= pluralize(@sub_forum.members.active_members.size, t("member_string")) %>
      </div>
      <div class="col-6" style="border-left: solid 1px;">
        <%= @sub_forum.posts.size %>
        <%= t "post_string" %>
      </div>
    </div>
    <% if current_user.nil? || !current_user.joined_forums?(@sub_forum) %>
      <%= form_for Member.new do |f| %>
        <%= hidden_field_tag :sub_forum_id, @sub_forum.id %>
        <%= f.submit t("join"), class: "btn btn-primary full-width" %>
      <% end %>
    <% elsif current_user? @sub_forum.user %>
      <%= link_to t("update"), edit_sub_forum_path(@sub_forum), class: "btn btn-primary full-width" %>
    <% else current_user.joined_forums?(@sub_forum) %>
      <%= form_for current_user.members.find_by(user_id: current_user.id, sub_forum_id: @sub_forum.id),
                   html: {method: :delete} do |f| %>
        <%= f.submit t("leave"), class: "btn btn-primary full-width" %>
      <% end %>
    <% end %>
    <%= link_to t("create_post"),
                nil, class: "btn btn-primary full-width" %>
  </div>
</div>

app/views/sub_forums/_sub_forum_member_list.html.erb
<% items.each do |item| %>
  <div class="card mb-3">
    <div class="row no-gutters">
      <div class="col-md-3">
        <div class="card-body">
          <%= image_tag "default.png", class: "rounded-circle card-img" %>
        </div>
      </div>
      <div class="col-md-9">
        <div class="card-body">
          <h5 class="card-title"><%= item.user.name %></h5>


          <% if item.user_type == Settings.admin_forum %>
            <p class="card-text">Admin</p>
          <% elsif item.user_type == Settings.mod_forum %>
            <p class="card-text">Mods</p>
            <%= form_for(item) do |f| %>
              <%= f.hidden_field :user_type, value: Settings.member_forum%>
              <%= f.submit "Unmod", class: "btn btn-primary float-right" %>
            <% end %>
          <% elsif item.user_type == Settings.member_forum %>
            <p class="card-text">Members</p>
            <%= form_for(item) do |f| %>
              <%= f.hidden_field :user_type, value: Settings.mod_forum %>
              <%= f.submit "Mod", class: "btn btn-primary float-right" %>
            <% end %>
          <% elsif item.user_type == Settings.banned_user %>
            <p class="card-text">Banned user</p>
            <%= form_for(item) do |f| %>
              <%= f.hidden_field :user_type, value: Settings.member_forum %>
              <%= f.submit "Unban", class: "btn btn-primary float-right" %>
            <% end %>
          <% end %>


          <% unless item.user_type == Settings.admin_forum || item.user_type == Settings.banned_user  %>
            <%= form_for(item) do |f| %>
              <%= f.hidden_field :user_type, value: Settings.banned_user %>
              <%= f.submit "Ban", class: "btn btn-danger float-right", style: "margin-right: 5px" %>
            <% end %>
          <% end %>
          <p class="card-text">
            <small class="text-muted">
              Joined since <%= time_ago_in_words(item.created_at) %>
            </small>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/sub_forums/_sub_forum_mod_list.html.erb
<div class="card">
  <div class="card-header">
    <%= yield(:header_text) %>
  </div>
  <ul class="list-group list-group-flush">
    <% @mods.each do |mod| %>
      <li class="list-group-item">
        <%= mod.user.name %>
      </li>
    <% end %>
  </ul>
</div>

app/views/sub_forums/edit.html.erb
<div class="row has-margin-row">
  <div class="col-3">
    <ul class="list-group">
      <li class="list-group-item active">Members</li>
      <li class="list-group-item">Posts</li>
      <li class="list-group-item">Mods</li>
    </ul>
    <br>
    <%= render "edit_sub_forum_form" %>
    <br>
  </div>
  <div class="col-9">
    <%= render "sub_forum_member_list", items: @admin %>
    <%= render "sub_forum_member_list", items: @mods %>
    <%= render "sub_forum_member_list", items: @normal_members %>
    <%= render "sub_forum_member_list", items: @banned_members %>
  </div>
</div>

app/views/sub_forums/new.html.erb
<%= form_for(@sub_forum, html: {class: "form-login-signup"}) do |f| %>
  <h2><%= t "brand" %></h2>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>

  <%= f.submit t("static_pages.home.create_sub_forum"), class: "btn btn-lg btn-primary btn-block" %>
<% end %>

app/views/sub_forums/show.html.erb
<div class="has-margin-row row">
  <div class="col-12">
    <div class="jumbotron">
      <h1 class="display-4"><%= @sub_forum.name %></h1>
      <p class="lead"><%= @sub_forum.description %></p>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-9">
      <%= render "post_preview_list", posts: @posts %>
  </div>

  <div class="col-3">
    <%= render "sub_forum_details" %>
    <% provide(:header_text, t("moderators")) %>
    <%= render "sub_forum_mod_list"%>
  </div>
</div>