config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  resources :users, only: %i(show new create update)
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :account_activations, only: :edit
  resources :sub_forums
  resources :password_resets, only: %i(new create edit update)
  resources :sub_forums
  resources :members, only: %i(create destroy update)
  resources :password_resets, only: %i(new create edit update)
  resources :members, only: %i(create destroy)
  get "/submit", to: "posts#new"
  post "/submit", to: "posts#create"
  resources :posts, only: %i(show update)
  post "/posts/:id", to: "post_interactions#update"
  get "/search", to: "searchs#new"
  get "/users/:id/created_sub_forums",
    to: "users#show_created_sub_forums", as: "created_sub_forums"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <%= link_to t("brand"), root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <ul class="navbar-nav mr-auto">
    <%= form_for :searchs, url: search_path, method: :get, html: {class: "form-inline my-2 my-lg-0"} do |f| %>
      <%= search_field_tag :q, nil, class: "form-control mr-sm-2" %>
      <%= f.submit t("search"), class: "btn btn-primary my-2 my-sm-0" %>
    <% end %>
  </ul>
  <% if logged_in? %>
    <ul class="navbar-nav">
      <li class="nav-item">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
              <%= t "welcome" %>, <%= current_user.name %> <b class="caret"></b>
            </a>
            <div class="dropdown-menu dropdown-menu-right position-absolute" aria-labelledby="navbarDropdown">
              <%= link_to t("log_out"), logout_path, method: :delete, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to t("your_profile"), current_user, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </li>
    </ul>
  <% else %>
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to t("log_in"), login_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to t("sign_up"), signup_path, class: "nav-link" %>
      </li>
    </ul>
  <% end %>
</nav>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= render "layouts/rails_default" %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container" style="margin-bottom: 50px;">
      <% flash.each do |message_type, message| %>
        <div aria-live="polite" aria-atomic="true" class="toast-area">
          <div class="toast" data-delay="2000">
            <div class="toast-header">
              <strong class="mr-auto"><%= message_type.upcase %></strong>
              <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="toast-body">
              <%= message %>
            </div>
          </div>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>